language: python
python:
  - "2.7.14"
install:
  - pip install ansible-lint
script:
  - ansible-lint setup-playbook.yaml
#  - ansible-lint test-playbook.yaml
#  - ansible-lint teardown-playbook.yaml
branches:
  only:
  - master
