---
- hosts: all
  user: "{{ remote_user }}"
  become: yes
  tasks:
  - name: Remove certificate
    file:
      path: "{{ cert_dir }}/webproxy.crt"
      state: absent

  - name: update_cert_index
    command: "{{ cert_bin }}"
    changed_when: false

  - name: get file stat to be able to perform check in the following task
    stat:
      path: /etc/systemd/system/kube-issue-32728-fix.service
    register: service_32728

  - name: Disable the fix for 32728
    systemd:
      name: kube-issue-32728-fix.service
      state: stopped
      enabled: no
    when: service_32728.stat.exists

  - name: Remove systemd unit file for 32728 fix (symlinks in /sys)
    file:
      path: /etc/systemd/system/kube-issue-32728-fix.service
      state: absent
    when: service_32728.stat.exists

  - name: Remove python bootstrap file
    file:
      path: "{{ ansible_pypy_bootstrap_file }}"
      state: absent

  - name: Remove python interpreter
    raw: "rm -rf {{ ansible_python_interpreter }} {{ ansible_pypy_home }}"

- hosts: masters:workers
  user: "{{ remote_user }}"
  become: yes
  tasks:
    - name: Remove kubernetes repository
      yum_repository:
        name: Kubernetes
        state: absent
      ignore_errors: yes 

    - name: Remove docker repository
      yum_repository:
        name: Docker
        state: absent
      ignore_errors: yes

    - name: Stop services
      command: timeout 15 /bin/systemctl stop {{ item }}
      loop:
        - kubelet
        - docker
      ignore_errors: yes
      changed_when: false

    - name: Disable services
      command: timeout 15 /bin/systemctl disable {{ item }}
      loop:
        - kubelet
        - docker
      ignore_errors: yes
      changed_when: false

    - name: Remove files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/systemd/system/docker.service.d
        - /etc/systemd/system/kubelet.service
        - /etc/kubernetes

    - name: Unmount docker net resources
      command: /bin/umount /run/docker/netns/*
      ignore_errors: yes

    - name: Unmount docker resources
      command: /bin/umount /var/lib/docker/overlay
      ignore_errors: yes
      register: unmount_result
      changed_when: false

    - name: Find overlay pids to kill
      shell: "lsof | grep '/var/lib/docker/overlay' | awk '{print $2}'"
      register: overlay_pids
      when: unmount_result.stderr | search("busy")

    - name: Kill running overlay pids
      shell: "kill -9 {{ item }}"
      loop: "{{ overlay_pids.stdout_lines|flatten(levels=1) }}"
      when: unmount_result.stderr | search("busy") and overlay_pids | length > 0

    - name: Get mounted kubelet resources
      shell: "mount | grep /var/lib/kubelet/pods | cut -d ' ' -f 3"
      register: kubelet_resources
      ignore_errors: yes
      changed_when: false
      tags:
        - skip_ansible_lint

    - name:  umount kubelet resources
      command: "umount {{ item }}"
      when: kubelet_resources.stdout_lines|length > 0
      loop: "{{ kubelet_resources.stdout_lines|flatten(levels=1) }}"

- hosts: masters
  user: "{{ remote_user }}"
  become: yes
  tasks:
    - name: Remove files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/sensu/conf.d/nais_master_metrics.json

- hosts: etcd
  user: "{{ remote_user }}"
  become: yes
  tasks:
    - name: Disable etcd
      systemd:
        name: etcd
        enabled: no
        state: stopped
      ignore_errors: yes

    - name: Remove files
      file:
        path: "{{ itemÂ }}"
        state: absent
      loop:
        - "{{ install_dir }}/bin/etcd-{{etcd_version}}"
        - "{{ install_dir }}/bin/etcd"
        - "{{ install_dir }}/bin/etcdctl-{{etcd_version}}"
        - "{{ install_dir }}/bin/etcdctl"
        - /var/lib/etcd
        - /etc/systemd/system/etcd.service
        - /etc/ssl/etcd

- hosts: workers
  user: "{{ remote_user }}"
  become: yes
  tasks:
    - name: Remove files
      file:
        path: /etc/sensu/conf.d/nais_worker_metrics.json
        state: absent

- hosts: localhost
  tasks:
    - name: Remove target folder
      file:
        path: target
        state: absent

- hosts: masters:workers
  user: "{{ remote_user }}"
  become: yes
  tasks:
  - name: Stop services
    systemd:
      name: "{{ item }}"
      state: stopped
      enabled: no
    loop:
      - kube-proxy
      - flannel
    ignore_errors: yes

  - name: Remove files
    file:
      path: "{{ item }}"
      state: absent
    loop:
      - /etc/systemd/system/kubelet.service
      - "{{ install_dir }}/bin/kube-proxy*"
      - "{{ install_dir }}/bin/kubelet*"
      - "{{ install_dir }}/bin/kubectl*"
      - /etc/systemd/system/kube-proxy.service
      - "{{ install_dir }}/libexec/mk-docker-opts.sh"
      - "{{ install_dir }}/bin/flanneld"
      - /etc/systemd/system/flannel.service
      - /etc/systemd/system/docker.service
      - "{{ install_dir }}/bin/flanneld-{{flannel_version}}"
      - /run/docker_opts.env
      - /run/flannel/subnet.env
      - /var/lib/docker
      - /var/lib/dockershim
      - /var/lib/kubelet
      - /var/lib/kubernetes
      - /var/run/flannel
      - /var/run/kubernetes
      - /run/flannel
      - /run/kubernetes
      - /root/.docker

  - name: Remove flannel interface
    command: ip link delete flannel.1
    ignore_errors: yes
    changed_when: false

  - name: Remove nais sensu check directory
    file:
      path: /etc/sensu/plugins/metrics/nais
      state: absent
